# Pandas Demo

This demo works through importing pandas and using it to research a csv file.  CSV file must be found and imported.

In [1]:
# Review class recording to find CSV on kaggle.  Most open CSV in VSC prior to importing.  Is there a military awards csv, MoH?

# Iports pandas and changes the name to shorthand pd
import pandas as pd

#create a dataframe object from a csv
# Takes already sorted CSV data and resorts for our use.
# tell pandas to read a file name within the () and 
moh_df = pd.read_csv('medal_of_honor.csv', delimiter=",")

moh_df

,death,name,awarded.General Order number,awarded.accredited to,awarded.citation,awarded.issued,birth.location name,metadata.link,military record.company,military record.division,...,awarded.date.day,awarded.date.full,awarded.date.month,awarded.date.year,awarded.location.latitude,awarded.location.longitude,awarded.location.name,birth.date.day,birth.date.month,birth.date.year
0,True,"Sagelhurst, John C.",-1,NaN,Under a heavy fire from the enemy carried off ...,01/03/1906,"Buffalo, N.Y.",http://www.cmohs.org/recipient-detail/1176/sag...,Company B,1st New Jersey Cavalry,...,6,1865-2-6,2,1865,38,-77,"Hatchers Run Court, Stafford, VA 22554, USA",-1,-1,-1
1,True,"Hack, John",-1,NaN,Was one of a party which volunteered and attem...,01/03/1907,"1843, Germany",http://www.cmohs.org/recipient-detail/537/hack...,Company B,47th Ohio Infantry,...,3,1863-5-3,5,1863,32,-90,"Vicksburg, MS, USA",-1,-1,-1
2,True,"Carson, Anthony J.",-1,NaN,Assumed command of a detachment of the company...,01/04/1906,"Boston, Mass.",http://www.cmohs.org/recipient-detail/2211/car...,Company H,43d Infantry,...,-1,-1--1--1,-1,-1,10,124,"Leyte, Philippines",-1,-1,-1
3,True,"Defranzos, Arthur F.",1,NaN,For conspicuous gallantry and intrepidity at t...,01/04/1945,"Saugus, Mass.",http://www.cmohs.org/recipient-detail/2710/def...,NaN,1st Infantry Division,...,10,1944-6-10,6,1944,49,0,"14490 Vaubadon, France",-1,-1,-1
4,True,"Kessler, Patrick L.",1,NaN,For conspicuous gallantry and intrepidity at r...,01/04/1945,"Middletown, Ohio",http://www.cmohs.org/recipient-detail/2824/kes...,Company K,"30th Infantry, 3d Infantry Division",...,23,1944-5-23,5,1944,43,11,"50026 Ponte Rotto FI, Italy",-1,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3470,True,"Yeager, Jacob F.",-1,NaN,Seized a shell with fuze burning that had fall...,?,"Lehigh County, Pa.",http://www.cmohs.org/recipient-detail/1531/yea...,Company H,101st Ohio Infantry,...,11,1864-5-11,5,1864,31,-81,"Buzzards Roost, Brunswick, GA 31520, USA",-1,-1,-1
3471,True,"Yntema, Gordon Douglas",-1,NaN,For conspicuous gallantry and intrepidity in a...,?,"Bethesda, Md.",http://www.cmohs.org/recipient-detail/3454/ynt...,Company D,5th Special Forces Group,...,-1,-1--1--1,-1,-1,10,106,Honorary Consulate General of the Republic of ...,26,6,1945
3472,True,"Young, Andrew J.",-1,NaN,Capture of flag.,?,"Greene County, Pa.",http://www.cmohs.org/recipient-detail/1532/you...,Company F,1st Pennsylvania Cavalry,...,5,1865-4-5,4,1865,37,-78,"Virginia, USA",-1,-1,-1
3473,True,"Young, Benjamin F.",-1,NaN,Capture of flag of 35th North Carolina Infantr...,?,"1844, Canada",http://www.cmohs.org/recipient-detail/1533/you...,Company I,1st Michigan Sharpshooters,...,17,1864-6-17,6,1864,37,-77,"Petersburg, VA, USA",-1,-1,-1
3474,True,"Young, Calvary M.",-1,NaN,Gallantry in capturing Gen. Cabell.,?,"Washington County, Ohio",http://www.cmohs.org/recipient-detail/1534/you...,Company L,3d Iowa Cavalry,...,25,1864-10-25,10,1864,38,-95,"Osage County, KS, USA",-1,-1,-1

In [ ]:
oscar_df.head(10)

In [ ]:
print(oscar_df['year_ceremony'].min())
print(oscar_df['year_film'].mean())
print(oscar_df['year_film'].max())

In [ ]:
# Gives arandom sample of data within the provided range
oscar_df.sample(10)

In [ ]:
oscar_df.describe(include='all')

In [ ]:
oscar_df['film'].value_counts()

In [ ]:
oscar_df['name'].value_counts()[:10]

In [ ]:
# Visualization.  Interested in film, 15 vaule counts, plots out as a bar horizontl, gives title of plot.  Pandas is great at making good looking visualizations.  Refer to pandas website.
oscar_df['film'].value_counts()[:15].plot(kind="barh", title="Most Oscar Nominated Films")

In [ ]:
# Utility function for running queries on data.  In this case searching awards without a film attached, ex lifetime achievement awards.
oscar_df['film'] = oscar_df['film'].fillna('No title available')

In [ ]:
# This queries all films with the word woman in the title.
oscar_df[oscar_df['film'].str.contains('Woman')]